global:
  scrape_interval: 5s # makes for a good demo

scrape_configs:
  - job_name: 'betsy-api'
    static_configs:
      - targets: ['host.docker.internal:5100'] # hard-coded port matches launchSettings.json
